### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by Amit-A** [cisagov/travis-wait-improved#5]
I'm getting this error:

```bash
Traceback (most recent call last):
  File "/home/travis/.local/bin/travis-wait-improved", line 6, in <module>
    from travis_wait_improved.sherpa import main
  File "/home/travis/.local/lib/python2.7/site-packages/travis_wait_improved/sherpa.py", line 29
SyntaxError: Non-ASCII character '\xe2' in file /home/travis/.local/lib/python2.7/site-packages/travis_wait_improved/sherpa.py on line 29, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

.travis.yml:

```yml
  ...
  before_deploy:
    - pip install travis-wait-improved --user
    deploy:
      skip_cleanup: true
      provider: script
      script: travis-wait-improved --timeout 30m bash scripts/travis_deploy.sh
      on:
        all_branches: true
  ...
```

When I tried without `--user`:

```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/docopt.py'
Consider using the `--user` option or check the permissions.
```

**Comment by Amit-A** [comment]
Cause is probably `❱` character:
```python
# line 29 in sherpa.py
HEADER = colored("Travis-wait ❱", "magenta", attrs=["bold"])
```

**Comment by mcdonnnj** [comment]
@Amit-A Thank you for taking the time to contribute. I see that your environment appears to be using Python 2.7, but this tool was written for Python 3.6+. Even if the special character was replaced you would run into issues with the [f-strings](https://www.python.org/dev/peps/pep-0498/) used later on in the tool.

**Comment by mcdonnnj** [comment]
Feel free to reopen this issue if you believe it is still a relevant change given the context I added.

**Comment by samos123** [comment]
the readme should point out that this tool only works on python3. I hit the exact same issue today.
